### ISSUE TITLE
Queries selection is biased towards search.

### ISSUE THREAD

**Issue by alexey-milovidov** [db-benchmarks/db-benchmarks#11]
Most of the queries are either using full-text search or selection by secondary indices (which is a beta feature of Manticore 5, released just a few days ago). This looks too cherry-picked in comparison to other database benchmarks.

**Comment by sanikolaev** [comment]
> Most of the queries are either using full-text search or selection by secondary indices

It depends on the test, e.g. in the logs test there are only [2 queries](https://github.com/db-benchmarks/db-benchmarks/blob/main/tests/logs10m/test_queries) out of 12 with `WHERE` (hn: 16/28, taxi - 9/17), so totally 27/57, not most :) But in general it's a fair point. Unfortunately there can't be any objective selection in any benchmark. It's always either a person or a group of people that decide that these queries should be included and others shouldn't or it's based on someone's application / real-world use case which may work or not work for others depending on how similar their application / use case is similar to the author's.

So the only thing which seems making sense to me now is to add a disclaimer to warn users that the final results can be not objective and should be used with caution. It's done: 

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/28719845/170920623-b66c5fca-d3c6-4061-8f53-4417463caf5a.png">

> selection by secondary indices (which is a beta feature of Manticore 5, released just a few days ago)

I've also updated the [blogposts](https://db-benchmarks.com/posts/) to add info about secondary indexes in Manticore. The blog posts were made earlier than this functionality was released in Manticore and we forgot to update them after retesting, thank you for pointing it out.

If there's an as easy way to enable secondary indexes as in Elasticsearch (enabled by default) and Manticore Search (one setting in config) in Clickhouse please let me know or make a PR. As I wrote in the blog posts I couldn't find an easy way for that for MySQL, Percona Server and Clickhouse.

I'm closing the issue as done. Feel free to re-open in case you have a better idea how to solve it in a better way.
