### ISSUE TITLE
I wonder if Test (data set) selection should come first? (instead of engines)

### ISSUE THREAD

**Issue by marclaporte** [db-benchmarks/db-benchmarks#14]
Given available test results depend on **Engines** and **RAM limit**, I wonder if we should put those above.

<img width="836" alt="2022-06-07-db-benchmarks-proposed-order" src="https://user-images.githubusercontent.com/1004261/172430887-4fb899ea-5db3-48dc-97ff-61d9283adeeb.png">

**Comment by sanikolaev** [comment]
Right. We are already working on a new layout of the menu. "Test" will indeed come first. In general it will look like this:

![image](https://user-images.githubusercontent.com/28719845/172539987-7a755ddd-4e15-43a5-a687-06c4ff60e3fd.png)

We'll close this issue when it's done.

**Comment by Nick-S-2018** [comment]
This is a test comment for Syncer

**Comment by Nick-S-2018** [comment]
Right. We are already working on a new layout of the menu. "Test" will indeed come first. In general it will look like this:

![image](https://user-images.githubusercontent.com/28719845/172539987-7a755ddd-4e15-43a5-a687-06c4ff60e3fd.png)

We'll close this issue when it's done.
