### ISSUE TITLE
Add database version number to the test results

### ISSUE THREAD

**Issue by marclaporte** [db-benchmarks/db-benchmarks#24]
Version changes, especially major versions, can have a significant impact on performance.

For example: "PHP 4 was fast, but lacked a lot of features that got implemented in PHP 5.0. These features made PHP 5.0 slower. PHP 5.1, 5.2 and 5.3 got optimized and are about 75% faster than 5.0." Source: https://onlinephp.io/benchmarks

Thus, https://db-benchmarks.com/ can entice the whole ecosystem to improve over time.

**Comment by sanikolaev** [comment]
Done
