### ISSUE TITLE
Add Typesense

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/db-benchmarks#34]

**Comment by djklim87** [comment]
* hn_small:
   * 110000 Works fine
   * 1024 Not enough resources

* hn
  Generally, Typesense indexing this dataset. But after the restart to became available it needed a huge amount of time (nearly 8 hours). It seems impossible to test an engine with behavior like that.
  
Also, it needs to make snaps for collections before restarting. In the worst case, if you perform the query - It will process it on the not full dataset (only that part that has already readed)

**Comment by djklim87** [comment]
Done in https://github.com/db-benchmarks/db-benchmarks/pull/35

**Comment by sanikolaev** [comment]
Merged. Published
