### ISSUE TITLE
Add Quickwit

### ISSUE THREAD

**Issue by sanikolaev** [db-benchmarks/db-benchmarks#36]

**Comment by djklim87** [comment]
* Sorting does not work properly. I should use Elasticsearch compatibility endpoints, that also not cover all functionality

**Comment by djklim87** [comment]
Waiting for approve https://github.com/db-benchmarks/db-benchmarks/pull/38/files

**Comment by sanikolaev** [comment]
We'll continue in https://github.com/db-benchmarks/db-benchmarks/pull/38
