### ISSUE TITLE
Feat: measure load while loading data

### ISSUE THREAD

**Issue by djklim87** [db-benchmarks/db-benchmarks#42]
We need to add measures for the init step (indexing) of each engine. 

We should measure:
* Time
* RAM consumption
* CPU consumption

And store these results in a different table from the main results. 
So we should probably improve `test.php` to use it for the init part

**Comment by djklim87** [comment]
Done in https://github.com/db-benchmarks/db-benchmarks/pull/48

**Comment by sanikolaev** [comment]
What issue blocks this one?

**Comment by sanikolaev** [comment]
In general looks good to me, but I requested minor changes in https://github.com/db-benchmarks/db-benchmarks/pull/48

**Comment by djklim87** [comment]
Done for UI in https://github.com/db-benchmarks/ui/commit/3b479cb789f1a108dd97f1a890cd6d288e895b64

**Comment by djklim87** [comment]
Done for db-benchmarks in https://github.com/db-benchmarks/db-benchmarks/commit/10a2d9de78dc9a74b6ae36b5d7814b1c444871e6
