### ISSUE TITLE
Table markup can be better.

### ISSUE THREAD

**Issue by alexey-milovidov** [db-benchmarks/db-benchmarks#9]
Now it looks like this:  
![image](https://user-images.githubusercontent.com/28719845/179207476-41d7803d-bdb8-4f4c-94ab-73ab9686282f.png)  

The horizontal position of the summary chart should be better aligned.  
The margin at the left is unneeded when the table does not fit on the page.

**Comment by marclaporte** [comment]
Thanks!  @RODRIGUErzed will fix this shortly.

**Comment by sanikolaev** [comment]
Done within https://github.com/db-benchmarks/ui/pull/18

**Comment by sanikolaev** [comment]
It looks like this now:

![image](https://user-images.githubusercontent.com/28719845/179676245-5cac5f64-34ac-4805-a2ed-aba20b8a5bd8.png)
